-- ============================================================
-- v1.66 - MANTENIMIENTO · PLAN PREVENTIVO + PARTES (Herrería)
-- Enriquece las gamas con el instructivo real (propósito / componente /
-- ejecución paso a paso / herramienta / consumible) y agrega el catálogo
-- de repuestos con foto por máquina. Carga las 11 máquinas de Herrería.
-- Correr DESPUES de v1.62/v1.63 (y v1.64/v1.65 si ya están). Idempotente.
-- ============================================================

-- 1) Columnas de instructivo en las gamas (aditivo) --------------------------
alter table public.mant_gamas add column if not exists tarea_tipo  text;
alter table public.mant_gamas add column if not exists proposito   text;
alter table public.mant_gamas add column if not exists componente  text;
alter table public.mant_gamas add column if not exists ejecucion   text;
alter table public.mant_gamas add column if not exists herramienta text;
alter table public.mant_gamas add column if not exists consumible  text;

-- 2) Tabla de componentes / repuestos (con foto en Storage) ------------------
create table if not exists public.mant_componentes (
  id         uuid primary key default gen_random_uuid(),
  activo_id  text not null references public.mant_activos(id) on delete cascade,
  cantidad   text,
  nombre     text not null,
  foto_path  text,                       -- ruta en bucket 'mantenimiento'; la imagen NUNCA va en la fila
  orden      integer not null default 0,
  creado_en  timestamptz not null default now()
);
create index if not exists idx_mant_componentes_activo on public.mant_componentes (activo_id);
alter table public.mant_componentes enable row level security;
drop policy if exists mant_componentes_select on public.mant_componentes;
drop policy if exists mant_componentes_write  on public.mant_componentes;
create policy mant_componentes_select on public.mant_componentes for select to authenticated using (true);
create policy mant_componentes_write  on public.mant_componentes for all to authenticated using (app_es_admin_mant()) with check (app_es_admin_mant());

-- 3) Bucket privado de fotos + políticas de Storage --------------------------
insert into storage.buckets (id, name, public) values ('mantenimiento','mantenimiento', false)
  on conflict (id) do nothing;
drop policy if exists mant_fotos_read   on storage.objects;
drop policy if exists mant_fotos_write  on storage.objects;
create policy mant_fotos_read on storage.objects for select to authenticated
  using (bucket_id = 'mantenimiento');
create policy mant_fotos_write on storage.objects for all to authenticated
  using (bucket_id = 'mantenimiento' and app_es_admin_mant())
  with check (bucket_id = 'mantenimiento' and app_es_admin_mant());

-- 4) Activos de Herrería que faltaban (los existentes no se tocan) -----------
insert into public.mant_activos (id, nombre, sector_id, planta_id, subarea, tipo, simbolo, criticidad, iit_ref) values
  ('HER-MALA-01','Malacate 1000 kg','her','cerdan_n1','Herrería',null,'aparejo','B','Plan mantenimiento Herrería'),
  ('HER-TRAN-01','Transportador aéreo','her','cerdan_n1','Herrería',null,'aparejo','B','Plan mantenimiento Herrería'),
  ('HER-SIEH-01','Sierra hidráulica para caño','her','cerdan_n1','Herrería',null,'sierra','B','Plan mantenimiento Herrería'),
  ('HER-BOXH-01','Box de hermeticidad','her','cerdan_n1','Herrería',null,'maquina','B','Plan mantenimiento Herrería'),
  ('SRV-AIRE-01','Aire comprimido para láser','srv','cerdan_n1','Herrería',null,'motor','A','Plan mantenimiento Herrería')
on conflict (id) do nothing;

-- 5) Gamas preventivas enriquecidas (86 tareas) --------------------------
delete from public.mant_gamas where activo_id in ('HER-AUTO-R1','HER-BOXH-01','HER-MALA-01','HER-MESB-M1','HER-RACK-01','HER-ROBS-01','HER-ROLA-01','HER-SIEH-01','HER-TRAN-01','SRV-AIRE-01','SRV-GRUA-01');
insert into public.mant_gamas (activo_id, tarea, frecuencia, responsable, tarea_tipo, proposito, componente, ejecucion, herramienta, consumible, orden) values
  ('HER-RACK-01','Limpieza: Guias de deslizamiento','mensual','mantenimiento','Limpieza','Eliminar polvo, grasa vieja o virutas de chapa. Una guia sucia aumenta la carga en un motor','Guias de deslizamiento','Interrumpa la corriente desde el tablero principal, luego con un trapo pase sobre las guias por donde corre las bandejas para eliminar todo tipo de suciedad. Repita el procedimiento para las 6 bandejas.','Trapos.',null,0),
  ('HER-RACK-01','Inspeccion: Sensor inductivo M18, finales de carrera chint YBLX-ME/8108','mensual','mantenimiento','Inspeccion','Inspeccion visual de los sensores para asegurar su correcto funcionamiento. El rack cuenta con dos sensores inductivos en la parte izquiera y derecha superior, para controlar la apertura y cierra de las puertas. Ademas, tiene dos finales de carrera por cada piso en la parte trasera, los cuales controlan la posicion del rack','Sensor inductivo M18, finales de carrera chint YBLX-ME/8108','Interrumpa la corriente desde el tablero principal, al abrir las puertas, en la parte superior derecha e izquierda se encuentran dos sensores inductivos, asegurese que estos se encuentran libres de polvo y en un estado correcto. Los sensores inductivos se deben estar de 5 a 20 mm de distancia de la puerta. Ademas, en las partes trasera de cada rack o piso se encuentran dos finales de carreras que son los encargados de marcar la distancia de recorrido de cada piso. En caso de que se encuentren en mal estado, tanto algun final de carrera como algun sensor inductivo, proceda a realizar el cambio del mismo.','Escalera, Pulsiana, destorillador Philips',null,1),
  ('HER-RACK-01','Inspeccion: Pulsador de arranque NA, pulsador de parada NA, pulsador de emergencia NC','mensual','mantenimiento','Inspeccion','Verifique el correcto funcionamiento de los pulsadores de emergencia','Pulsador de arranque NA, pulsador de parada NA, pulsador de emergencia NC','Con el rack energizado, compruebe el funcionamiento de cada uno de los botones de parada del sistema.',null,null,2),
  ('HER-RACK-01','Limpieza: Bornes del tablero principal','mensual','mantenimiento','Limpieza','Aspirado de polvo y reapriete de conexiones para evitar falsos contactos.','Bornes del tablero principal','Con el tablero desenergizado, asegure cada uno de los bornes de las conexiones del tablero, debido a que con el tiempo y las vibraciones, estas se pueden aflojar provocando falsos contactos y sobrecalentamiento','Destornillador philips, taladro electrico.',null,3),
  ('HER-RACK-01','Revision: 6 cajas reductoras','trimestral','mantenimiento','Revision','Revisar el nivel de aceite de las cajas reductoras y limpiar el cuerpo para evitar sobrecalentamiento','6 cajas reductoras','Desmonte los 4 tornillos allen que tiene en la tapa, gire el eje cuidadosamente con la mano para ver como actua la grasa, la misma debe de tener un color uniforme y no debe contener sedimentos. En caso que encuentre la grasa en mal estado, procure realizar el cambio.','Juego de llaves allen, trapo',null,4),
  ('HER-RACK-01','Cambio de aceite: 24 Rodamientos con lubricacion por alemite.','trimestral','mantenimiento','Cambio de aceite','Aceitar los rodamientos por los alojamientos (alemites) que tienen, asi se asegura su vida util. Se debe utilizar una grasera manual','24 Rodamientos con lubricacion por alemite.','Por la parte trasera de la maquina, se encuentra la caja reductora es la que genera el moviemiento de los ejes, estos mismos ejes estan enclavados con 4 rodamientos cada uno, dos de cada lado. Los rodamientos se encuentran sobre una cuna, los cuales pueden ser lubricados a traves de un alemite. Retire el pico verde de proteccion que tiene el alemite y proceda a engrasar los rodamientos, debe de hacerlo con una engrasadora manual, dandole 2 o 3 bombeadas de forma lenta.','Grasera engrasadora manual con pico para alemite.','Grasa multiuso. (ej: Grasa Shell Gadus S2 V220 2',5),
  ('HER-RACK-01','Cambio de grasa.: 6 cajas reductoras','anual','mantenimiento','Cambio de grasa.','Debe realizar una inspeccion del estado de la grasa semiliquida que utilizan estas cajas de engranajes, vienen lubricadas por fabrica para toda la vida. Puede suceder que con el paso del inicie un ruido molesto o perder grasa por sus propios retenes.','6 cajas reductoras','Desmonte los 4 tornillos allen que tiene en la tapa, limpie cuidadosamente con un trapo limpio sin dejar restos  e introduzca la grasa nueva, colocando una porcion de entre el 30 y 50% del volumen del carter. En este caso debe colocar de 40 a 60 gr de grasa para que el nivel sea el optimo','Juego de llaven allen, trapo','Grasa semifluido sinitetica NLGI 00 para motorreductores',6),
  ('HER-ROLA-01','Limpieza: 4 rodillos moviles','mensual','mantenimiento','Limpieza','Eliminar escamas de metal, oxido o suciedad que se encuentre en la superficie de los rodillos dejandolo con una superficie lisa y pareja','4 rodillos moviles','Interrumpa la corriente desde el tablero principal, luego inspeccione visualemente los rodillos de la roladora, procure eliminar restos de metal, oxido o suciedad que van a ir provocando las chapas roladas.','Espatula, trapos, aire comprimido',null,7),
  ('HER-ROLA-01','Engrase: Rodamientos de los ejes','mensual','mantenimiento','Engrase','Engrase de soportes de rodamientos a través de los picos de engrase para asegurar el sellado de los rodamientos y el soporte seguro de las cargas.','Rodamientos de los ejes','Con la grasera, a traves de los huecos que contienen los soportes de los rodamientos, introduzca el pico de la misma y luego  realice dos bombeos de grasa. Retire y limpie el sobrante del pico con un trapo','Grasera, trapo','Grasa de Litio NLGI 2',8),
  ('HER-ROLA-01','Inspeccion: Pulsador de arranque NA, pulsador de emergencia NC, pulsador de parada NC','mensual','mantenimiento','Inspeccion','Verifique el correcto funcionamiento de los pulsadores de emergencia','Pulsador de arranque NA, pulsador de emergencia NC, pulsador de parada NC','Con la roladora energizada compruebe el funcionamiento de cada uno de sus botones.',null,null,9),
  ('HER-ROLA-01','Limpieza: Bornes del tablero principal','mensual','mantenimiento','Limpieza','Aspirado de polvo y reapriete de conexiones para evitar falsos contactos.','Bornes del tablero principal','Con el tablero desenergizado, asegure cada uno de los bornes de las conexiones del tablero, debido a que con el tiempo y las vibraciones, estas se pueden aflojar provocando falsos contactos y sobrecalentamiento.','Destornillador Philips.',null,10),
  ('HER-ROLA-01','Limpieza: Electrovalvulas','mensual','mantenimiento','Limpieza','Asegurese el buen estado de las electrovalvulas que se encuentran sobre el deposito de aceite. Elimine todo tipo de mugre que esten sobre los solenoides y la misma valvula.','Electrovalvulas','Con la maquina desenergizada, limpie cuidadosamente las electrovalvulas que se encuentran dentro del gabinete, asegurese que no existen perdidas de aceite.','Trapos.',null,11),
  ('HER-ROLA-01','Revision: Filtro de aceite','trimestral','mantenimiento','Revision','Revise el nivel de aceite y el estado en que se encuentran las mangueras, esto es vital para el funcionamiento de la maquina.','Filtro de aceite','Abra el gabinete donde se encuentra el deposito de aceite, en la parte superior encontrara un tapon, desenrosque, luego con un juego de llaven allen reitre la el aro del filtro para poder retirarlo. Una vez retirado, con un trapo seco limpie el filtro de todo tipo de sedimentos y restos solidos que quedaron en el.','Trapos, destornillador plano, juego llaves allen',null,12),
  ('HER-ROLA-01','Inspeccion: Rodillos de rolado','anual','mantenimiento','Inspeccion','Revise la alineacion de los rodillos para verificar un rolado parejo','Rodillos de rolado','Con un comparador asegure que las 4 superficies de rolado son parejas y no presentan una gran diferencia de medida.','Comparador',null,13),
  ('HER-ROLA-01','Cambio de aceite de sistema hidraulico: Aceite hidrauilico','anual','mantenimiento','Cambio de aceite de sistema hidraulico','Cambie el aceite del sistema hidraulico, con el tiempo el mismo pierde sus propiedades','Aceite hidrauilico','Con la roladora previamente usada, para licuar mas aun el aceite, lleve todos los cilindros a su posicion de reposo (altura minima). Luego retire la tapa del deposito de aceite que se encuentra en el gabinete, con una bomba de trasvase aspire todo el aceite del deposito, luego limpielo cuidadosamente con un trapo de microfibra sin dejar restos que podrian dañar las electrovalvulas. Proceda a llenar con aceite nuevo al deposito, encienda la maquina y realice ciclos completos para purgarla.','Bomba de trasvase, trapo de microfibra, juego llave allen.','Aceite hidraulico industrial (ej: Aceite Shell Tellus 68 Hidraulico Balde 20 Litros)',14),
  ('HER-AUTO-R1','Reemplazo: Pico de antorcha (Semanal (60hs arco activo))','semanal','mantenimiento','Reemplazo','Orificio ovalado o deformado por fricción, micro-pegaduras del alambre dentro del pico, arco inestable o falta de penetración.','Pico de antorcha','Corte la corriente de la maquina directamente del tablero. Comience desenroscando la tobera de forma lenta y tirando hacia abajo, proceda con el corte del sobrante de alambre al ras del pico. Luego con una pinza tome por las caras planas al pico y desenrosque cuidadosamente, aproveche y limpie la rosca del difusor. Luego enrosque el pico nuevo con la mano hasta que sienta que haga tope, termina de enroscar con la pinza sin realizar una fuerza excesiva y finalmente reinstala la tobera.','Pinza cuadrada, trapos, guantes','Pico de antorcha',15),
  ('HER-AUTO-R1','Lubricacion: Guias','semanal','mantenimiento','Lubricacion','Es muy importante tener las guias lubricadas y limpias, al igual que los patines, debido a que si las guías están secas, el cabezal de soldadura avanza dando micro-saltos imperceptibles a simple vista. Estos tirones alteran la velocidad de avance, produciendo un cordón de soldadura irregular, con porosidades, variaciones en el penetrado o discontinuidades. La grasa no solo lubrica, sino que actúa como una barrera o sello. Al inyectar grasa nueva, esta empuja hacia el exterior el humo, las chispas, las proyecciones y el polvo metálico que intentan entrar a los rodamientos del patín.','Guias','Limpie con un trapo seco y libre de pelusas las guias para elimarle todo tipo de grasa, aceite y mugre vieja. Una vez asegurada una superficie lisa y limpia. Luego con otro trapo, haga una fina capa de aceite sobre las guias, de forma tal que deben de quedar brillantes, no chorrenado. Es importante que solo se encuentren humedecidas ya que si se excede de aceite puede generar una pasta abrasiva a la cual se le acumula mugre de forma periodica y eventualmente romper los patines.','Trapo,aire comprimido','Aceite para guias , ej: Shell Tonna S3 M 68',16),
  ('HER-AUTO-R1','Deteccion: Tubo de gas','mensual','mantenimiento','Deteccion','La deteccion de fuga es clave, ya que al existir una fuga en el cabezal o regulador de gas esto genera un efecto negativo en el resultado final de la soldadura. Ademas, existe un desperdicio economico del gas y aprovechamos al 100% la vida util del cabezal regulador.','Tubo de gas','Mezcle agua con jabon, y pase en las conexiones de mangueras que tenga  para comprobar que no existe fuga de gas.','Jabon, agua.',null,17),
  ('HER-AUTO-R1','Inspeccion: Pulsador de inicio NA, pulsador de parada NC, pulsador de emergencia NC','mensual','mantenimiento','Inspeccion','Verifique el correcto funcionamiento de los pulsadores de emergencia','Pulsador de inicio NA, pulsador de parada NC, pulsador de emergencia NC','Con la maquina encendida, realice una prueba de soldadura y compruebe, mientras la maquina esta trabajando que sus botones de emergencia funcionan correctamente, los mismos deben de cortar el ciclo de trabajo.',null,null,18),
  ('HER-AUTO-R1','Remplazo: Tobera','mensual','mantenimiento','Remplazo','Acumulación severa de proyecciones que obstruya el flujo de gas, deformación física o fugas de gas por mala rosca/asiento.','Tobera','Corte la corriente de la maquina directamente del tablero, una vez la tobera enfriada con la temperatura ambiente, desenrosquela con cuidado. Una vez retirada limpie el pico de contacto y el difusor de gas, retirandole el ollin y restos de soldadura. Con la zona ya limpia busque la nueva tobera y enrosque con cuidado sin demasiado fuerza para no barrer ninguna rosca.','pinza cuadrada, trapos, guantes','Tobera',19),
  ('HER-AUTO-R1','Lubricacion: Patines','mensual','mantenimiento','Lubricacion','Dentro de cada patín hay decenas de bolas o rodillos de acero que recirculan continuamente a alta presión sobre la pista del riel. La grasa crea una película microfina de separación entre estos elementos. Sin esta capa, la fricción directa genera un desgaste acelerado que destruye la pista mecanizada y crea "juego" o holgura en el sistema.','Patines','La soldadora automatica de cubas rurales, cuenta con movimiento en los 3 ejes cartesianos (X,Y,Z). El movimiento de estos ejes, se realiza mediante patines sobre guias lineales. Primero, debe realizar una limpieza de las guias con un trapo y asegurarse que la superficie esta en buen estado y sin mugre. Luego en los mismos patines existen prisioneros estilo allen que deben ser retirados para poder lubricar, una vez retirado los prisioneros, con una grasera manual inyecte dos bombeadas de forma lenta dentro de cada agujero del patin, luego desplacelo por la guia para que la grasa se distribuya de forma uniforme sobre los elementos rondantes.','Trapo, juego de llave allen, Grasera engrasadora manual','Shell Gadus S2 V220 2',20),
  ('HER-AUTO-R1','Reemplazo: Difusor de gas (portapico)','trimestral','mantenimiento','Reemplazo','Rosca barrida, picaduras por calor intenso o poros obstruidos que no se pueden limpiar.','Difusor de gas (portapico)','Corte la corriente de la maquina directamente del tablero, una vez la tobera enfriada con la temperatura ambiente, desenrosquela con cuidado. Una vez retirada limpie el pico de contacto y el difusor de gas, retirandole el ollin y restos de soldadura. Con la zona ya limpia, desenrosque el difusor del cuello de la antorcha, limpie el cuello y la rosca de la antorcha antes de montar el repuesto, una vez la zona limpia ajuste con los dedos al difuros, luego termine de ajustar con una pinza, finalmente reinstale la tobera y el pico de la antorcha.','Pinza cuadrada, trapos, guantes','Difusor de gas',21),
  ('HER-AUTO-R1','Cambio de aceite: Caja reductora TongYu RV63','anual','mantenimiento','Cambio de aceite','Realice el cambio de aceite de caja reductora, debido a que es la intervención de mantenimiento mecánico más crítica para garantizar la precisión del movimiento y la supervivencia del reductor. Con el paso del tiempo y el uso de la caja, los engranajes internos se degradan por eso es de vital importancia el uso de aceite.','Caja reductora TongYu RV63','En la parte superior de la caja reductora se encuentra un tornillo allen, el cual es el tapon por el cual debe ingresar a la caja, en la parte inferior hay otro allen que es el encargado de drenar el aceite usado. Como primer paso, afloje y retire el tapon de drenado, retire el aceite colocandolo en un recipiente, aproveche a observar el estado y color, asi como tambien el tamaño de particulas que se encuentran en el mismo. Una vez retirado todo el aceite rellene con 300 ml de aceite nuevo tipo Shell Omala S4 WE 320','Juego de llaves allen, trapos, recipiente','Shell Omala S4 WE 320',22),
  ('SRV-GRUA-01','Inspeccion: Cable de acero del polipasto','mensual','mantenimiento','Inspeccion','Realizar la inspeccion del estado del cable de acero es sumamente importante, un puente grúa de 10 toneladas mueve cargas pesadas que, en caso de caída por rotura del cable, causan daños fatales al personal de planta o la destrucción total de las máquinas que se encuentran debajo. El cable de acero, no suele fallar de un segundo a otro sin dar avisos previos. Antes de romperse, el cable muestra señales progresivas, como primeros hilos rotos visibles, reducción del diámetro por fatiga en el alma interna, etc. Detectar estas fallas en la inspección mensual permite retirar el cable de servicio antes de llegar al punto crítico de ruptura con carga colgada','Cable de acero del polipasto','Baje el polipasto la mayor cantidad de altura que pueda para tener la mayor cantidad de cable de acero a la vista. Mida el diametro del cable con un calibre en tres tramos diferentes, cerca del gancho, en la parte central y cerca del motor. Asegurese que el diametro no cambia en un 10% con respecto a la medida original. Ademas, debe controlar que no existen hilos de acero rotos, ni corrosion en todo el tramo del cable. Una vez realizada la inspeccion limpie la grasa vieja saturada de polvo y aplique un lubricante para cadenas. El lubricante debe de colocarlo en lugares donde se abre, o se ve el alma del cable, estos lugares son como el ingreso a la polea del polipasto o en el ingreso del tambor donde se enrolla, creando una fina pelicula de lubricante en el cable.','Tijera o manipulador, calibre, guantes, lubricante, trapo','Loctite LB 8011',23),
  ('SRV-GRUA-01','Inspeccion: Pulsadores, receptor inalambrico.','mensual','mantenimiento','Inspeccion','Verifique el correcto funcionamiento de los pulsadores de emergencia','Pulsadores, receptor inalambrico.','Con el pulsador de inicio del control inalambrico del puente grua, habilita a que pueda iniciar a moverse en todas direcciones, una vez que verifico el inicio, pulse el boton de parada, el mismo desabilitara cualquier tipo de movimiento que quiera realizar, lo mismo sucedera con el pulsador de emergencia. En caso de que alguno de los botones no funcione, debe de abrir el control remoto con un destornillador philips y verificar que sus pistas y conexiones se encuentran sanas. En caso que el control no tenga ningun tipo de inconveniente, debe de subir y revisar la bornera de conexiones del receptor, en la misma debe de realizar un reaprite de cada uno de los bornes.','Destornillador Philips, tijera o manipulador.',null,24),
  ('SRV-GRUA-01','Inspeccion: Ruedas y guias rieles de movimiento de puente grua','mensual','mantenimiento','Inspeccion','Revise el desgaste en las pestañas de las ruedas y la alineacion de las vias','Ruedas y guias rieles de movimiento de puente grua','En los movimiento que realiza el puente grua, se observa que del lado motriz el movimiento es con ruedas dentadas, y luego del lado conducido el movimiento se genera con ruedas acanaladas. Limpie la grasa acumulada entre los dientes con una espatula y luego pasele un trapo limpio, luego aplique una fina capa de grasa adhesiva para engranajes como el loctite lb 8120. Asegurese que el riel se encuentre en buen estado y limpio. Del lado opuesto a estas ruedas dentadas, se encuentran las ruedas conducidas, estas ruedas deben de estar limpias y secas, no debe agregar grasa ni aceite. Para las guias que corren al carro norte/sur debe realizar la misma tarea, asegurarse que se encuentren en buen estado y limpias, pasele un cepillo de acero a traves de toda la guia y luego un trapo seco.','Espatula, destornillador plano, trapos, grasa para engranajes, cepillo de acero, trapos','Loctite Lb 8120 Grasa Adhesiva',25),
  ('SRV-GRUA-01','Limpieza: Tablero de potencia y control','mensual','mantenimiento','Limpieza','Aspirado de polvo y reapriete de conexiones para evitar falsos contactos','Tablero de potencia y control','Corte la termica general que energiza al tablero seccional donde se encuentra una llava termomagnetica del puente grua. Con el manipulador o tijera suba hasta el tablero de asegurese que los componentes se encuentran en buen estado y no existe sobrecalentamiento dentro del gabinete, ademas con un taladro electrico y guantes de seguridad realice el reaprite de conexiones de las borneras, debido a que con las vibraciones se pueden aflojar y crear falsos contactos.','Manioulador o tijera, taladro electrico',null,26),
  ('SRV-GRUA-01','Inspeccion: Cableado guirnalda','trimestral','mantenimiento','Inspeccion','Compruebe que el cable no trabaja de forma tensa ni muy holgada cuando el polipasto realiza algun movimiento, esto puede romper la aislacion del cable o desconectarlo, provocando la perdida de alimentacion del sistema','Cableado guirnalda','Corte energia del puente grua desde la termica que se encuentra en el tablero. Suba con una tijera o manipulador. Limpie e inspeccione la guia por donde corre el cableado guirnalda, limpie todo tipo de grasa y polvo que se encuentra sobre el riel. Inspeccione los rodamientos que giran sobre la guia, estos mismos no deben de tener ningun tipo de juego u holgura. En caso de que exista, reemplace el rodamiento por otro igual. Inspeccione todo el cable y asegure que las condiciones en la que se encuentra son las optimas. Por ultimo, deje una misma distancia entre cada bucle del cable, para que la fuerza se realice de forma uniforme a medida que el cable vaya corriendo por la guia','Tijera o manipulador, juego de tubos y cricket, trapo, grasa, destornillador philips',null,27),
  ('SRV-GRUA-01','Cambio de aceite: Cajas reductoras','anual','mantenimiento','Cambio de aceite','Realice el cambio de aceite de caja reductora, debido a que es la intervención de mantenimiento mecánico más crítica para garantizar la precisión del movimiento y la supervivencia del reductor. Con el paso del tiempo y el uso de la caja, los engranajes internos se degradan por eso es de vital importancia el uso de aceite.','Cajas reductoras','Realice el cambio de aceite una vez terminado de usar el puente grua para que el aceite este tibio y fluya con facilidad arrastrando todos los sedimentos. Coloque un recipiente en la parte inferior de la caja, y afloje el tapon de drenaje de aceite, una vez retirado cierre el tapon de drenaje, y abra el de llenado, llene con aceite hasta la medida que indica el visor o hasta que vea que ingreso la misma cantidad de aceite que fue expulsado.','Juego de llave allen, tijera o manipulador, trapos','Grasa para engranajes industriales (ej: Shell Omala S2 G 220 X 20)',28),
  ('HER-MALA-01','Inspeccion: Gancho de seguridad','semanal','mantenimiento','Inspeccion','Confirme que el gancho de carga no esta fisurado ni doblado','Gancho de seguridad','Compruebe que los ganchos de seguridad no presentan sintomas de ruptura. Debe comprobar que el gancho puede girar 360° sobre su eje sin girar y destrenzar el cable de acero. Ademas compruebe que el gancho no se encuentra abierto por levantar una carga que excede su fuerza. Compruebe que el pestillo del gancho esta en buenas condiciones, debido a que si debe manipular una carga con eslinga, la auscencia del pestillo podria provocar que la eslinga se deslice y salga del gancho',null,null,29),
  ('HER-MALA-01','Inspeccion: Control inalambrica y receptor','mensual','mantenimiento','Inspeccion','Verifique el correcto funcionamiento de los pulsadores de emergencia','Control inalambrica y receptor','Con el pulsador de inicio del control inalambrico del malacate, habilita a que pueda iniciar a moverse, una vez que verifico el inicio, pulse el boton de parada, el mismo desabilitara cualquier tipo de movimiento que quiera realizar, lo mismo sucedera con el pulsador de emergencia.',null,null,30),
  ('HER-MALA-01','Limpieza: Motor electrico','mensual','mantenimiento','Limpieza','La acumulacion de polvillo y mugre del ambiente se acumulara sobre la carcasa del motor y las aletas de refrigeracion, provocando sobrecalentamiento de los motores.','Motor electrico','Con el manipulador electrico o tijera suba hasta el malacate, con un destornillador philips retire la carcasa negra que cubre las aletas de refrigeracion, con un trapo limpio y seco remueva la mugre de las aletas. Realice la limpieza de la carcasa del motor.','Destornillador Philips, tijera o manipulador, trapos.',null,31),
  ('HER-MALA-01','Inspeccion: Ruedas y guias de movimiento del malacate','mensual','mantenimiento','Inspeccion','Verificar la ausencia de corrosión en las estructuras de la grúa y carro, así como en los elementos de acoplamiento al polipasto. En caso de aparición de óxido rojo reparar el elemento.','Ruedas y guias de movimiento del malacate','En los movimientos que realiza el malacate se observa que del lado motriz el movimiento es con ruedas dentadas, y luego del lado conducido el movimiento se genera con ruedas acanaladas. Limpie la grasa acumulada entre los dientes con una espatula y luego pase un trapo limpio, aplique una fina capa de grasa adhesiva para engranajes como el loctite lb 8120. Asegurese que el riel se encuentre en buen estado y limpio. Del lado opuesto a estas ruedas dentadas, se encuentran las ruedas conducidas, estas ruedas deben de estar limpias y secas, no debe agregar grasa ni aceite.','Espatula, destornillador plano, trapos, grasa para engranajes, cepillo de acero, trapos','Loctite Lb 8120 Grasa Adhesiva',32),
  ('HER-MALA-01','Inspeccion: Cable de acero trenzado del polipasto','mensual','mantenimiento','Inspeccion','Realizar la inspeccion del estado del cable de acero es sumamente importante, un puente grúa de 10 toneladas mueve cargas pesadas que, en caso de caída por rotura del cable, causan daños fatales al personal de planta o la destrucción total de las máquinas que se encuentran debajo. El cable de acero, no suele fallar de un segundo a otro sin dar avisos previos. Antes de romperse, el cable muestra señales progresivas, como primeros hilos rotos visibles, reducción del diámetro por fatiga en el alma interna, etc. Detectar estas fallas en la inspección mensual permite retirar el cable de servicio antes de llegar al punto crítico de ruptura con carga colgada','Cable de acero trenzado del polipasto','Baje el polipasto la maxima cantidad de altura que pueda para tener la mayor cantidad de cable de acero a la vista. Mida el diametro del cable con un calibre en tres tramos diferentes, cerca del gancho, en la parte central y cerca del motor. Asegurese que el diametro no cambia en un 10% con respecto a la medida original. Ademas, debe controlar que no existen hilos de acero rotos, ni corrosion en todo el tramo del cable. Una vez realizada la inspeccion limpie la grasa vieja saturada de polvo y aplique un lubricante para cadenas. El lubricante debe de colocarlo en lugares donde se abre, o se ve el alma del cable, estos lugares son como el ingreso a la polea del polipasto o en el ingreso del tambor donde se enrolla, creando una fina pelicula de lubricante en el cable.','Tijera o manipulador, calibre, guantes, lubricante, trap','Loctite LB 8011',33),
  ('HER-MALA-01','Inspecicon: Cableado guirnalda','trimestral','mantenimiento','Inspecicon','Compruebe que el cable no trabaj de forma tensa ni muy holgada cuando el polipasto realiza algun movimiento, esto puede romper la aislacion del cable o desconectarlo, provocando la perdida de alimentacion del sistema','Cableado guirnalda','Limpie con un trapo seco la guia por donde se deslicen los aros que sostienen el cable, inspeccione el cable de alimentacion que pase a traves de estos. En caso que el cable o algun aro se encuentre en mal estado proceda a realizar el cambio.','Tijera o manipulador, alicate, pinza, trapos.',null,34),
  ('HER-MALA-01','Cambio de aceite: Caja reductora','anual','mantenimiento','Cambio de aceite','Los rodamientos del motor eléctrico son rodamientos blindados que vienen con su propia grasa sintética cargada desde la fábrica y no se pueden ni se deben reengrasar por fuera. La caja reductora que se encuentra en la carcasa de aluminio (la parte gris plateada al costado del motor) no utiliza aceite fluido con tapones de nivel, sino grasa semifluida de litio. Viene hermética para evitar fugas en cualquier posición.','Caja reductora','Retire los tornillos de la carcasa de las aletas con un destornillador Philips, luego retire los 4 tornillos largos que unen la caja reductora con el eje. Una vez retirado limpie con un trapo seco y limpio la grasa vieja, coloque la grasa nueva y cierre nuevamente el motor.','Destornillador Philips, tijera o manipulador, trapos,','Grasa nlgi 00 o grasa nlgi 01',35),
  ('HER-TRAN-01','Limpieza: Riel tipo IPN','mensual','mantenimiento','Limpieza','La limpieza de los rieles por donde se deslizaran las ruedas es de vital importancia, debido a que asi se asegura un deslizamiento correcto de la carga que estara suspendida en el aire, un riel limpio representa un movimiento lineal constante y sin perturbaciones','Riel tipo IPN','Corte la energia del tablero principal, luego con una plataforma, suba hasta la altura del IPN por donde corren las ruedas, con un pincel y cepillo de acero, procupre que la pista quede totalmente uniforme y libre de grumos y aceite.','Plataforma elevadora, cepillo de acero, pincel, trapos',null,36),
  ('HER-TRAN-01','Inspeccion: Soportes de fundicion','trimestral','mantenimiento','Inspeccion','Los soportes son los encargados de soportar el peso de la carga que tendra movimiento en la linea. Es de vital importancia que las mismas se encuentren en buen estado','Soportes de fundicion','Corte la energia del tablero principal, luego con una plataforma suba hasta la altura de los soportes de fundicion. Compruebe que el estado en el que se encuentran es optimo, no debe presentar microfisuras ni grietas. En caso que presente alguna irregularidad, debe aflojar con una pulsiana el bulon con tuerca autofrenante que sostienen al soporte. Una vez quitado el bulon el soporte saldra facilmente.','Plataforma elevadora, cepillo de acero, pulsiana, juego de llaves, trapos',null,37),
  ('HER-TRAN-01','Inspeccion: Ruedas guias, 35mm ancho 130 mm diametro','trimestral','mantenimiento','Inspeccion','Controle el diametro de las ruedas y el ancho.','Ruedas guias, 35mm ancho 130 mm diametro','Corte la energia del tablero principal, luego con una plataforma suba hasta la altura de las ruedas guias. Comprueba que su espesor no disminuyo mas de 5 mm, observe que no existen deformaciones ni un mal contacto con el riel. Para desmontar la rueda en caso que existan deformaciones o grietas, con la pulsiana debera de aflojar el bulon que se encuentra en el centro, mientra con el juego de llaves agarra la tuerca que se encuentra del otro lado. Una vez extraida la rueda nueva coloque la nueva haciendo coincidir los agujeros.','Plataforma elevadora, cepillo de acero, pulsiana, juego de llaves, trapos',null,38),
  ('HER-TRAN-01','Inspeccion: Eslabones de cadena','mensual','mantenimiento','Inspeccion','Controle los eslabones de la cadena debido a que estos son los encargados de realizar la fuerza de traccion que hara mover linealmente a la carga.','Eslabones de cadena','Corte la energia del tablero principal, luego con una plataforma suba hasta la altura de la cadena. Debe observar que todos los eslabones no presentan fisuras ni estiramiento.','Plataforma elevadora, cepillo de acero, trapos.',null,39),
  ('HER-TRAN-01','Inspeccion: Piñones, engranajes, cadena','mensual','mantenimiento','Inspeccion','Controle que los el piñon que translada la fuerza del motor no esta barrida y tiene un buen enganche con los engranajes que haran girar luego la cadena.','Piñones, engranajes, cadena','Corte la energia del tablero principal, luego con una plataforma suba hasta la altura del piñon y corona, compruebe que estos no tienen juego libre y su enganche es el adecuando. Observe ademas, que los dedos que transladan la energia desde el juego de corona y piñon hacia el encadenado final, es optimo.','Plataforma elevadora',null,40),
  ('HER-TRAN-01','Lubricacion: Piñon, engranaje, cadena','trimestral','mantenimiento','Lubricacion','Aplicacion de lubricante sintetico a corona y piñon para prevenir calentamientos y roces con fuerza excesiva','Piñon, engranaje, cadena','Con una espatula y un trapo seco elimine toda la grasa acumulada en el sistema de engranjes, una vez todo limpie aplique una capa de grasa sobre las superficie de contacto entre el piñon y corona, limpie el exceso para evitar goteos de grasa o aceite sobre la carga.','Plataforma elevadora, espatula, destornillador plano, trapos','Shell Gadus S2 OG V220AD 2',41),
  ('HER-TRAN-01','Lubricacion: Rodamientos','anual','mantenimiento','Lubricacion','Aplicacion de lubricante a los rodamientos que se encuentran en la transmision de potencia (corona piñon)','Rodamientos','Apague el sistema desde el tablero, suba con una plataforma elevadora hasta la caja reductora, observe que cada uno de los ejes de transmision de potencia contienen un rodamiento con un asiento, el cual contiene un alemite por el cual debe ser engrasado. Con la engrasadora manual inyecte 2 bombeadas de grasa hacia los rodamientos, luego limpie la superficie.','Plataforma elevadora, trapo, grasera manual.','Grasa de Litio Multipropósito de Consistencia NLGI 2 con aditivos EP',42),
  ('HER-TRAN-01','Cambio de aceite: Caja reductora','anual','mantenimiento','Cambio de aceite','Realice el cambio de aceite de caja reductora, debido a que es la intervención de mantenimiento mecánico más crítica para garantizar la precisión del movimiento y la supervivencia del reductor. Con el paso del tiempo y el uso de la caja, los engranajes internos se degradan por eso es de vital importancia el uso de aceite.','Caja reductora','Baje la termica general que se encuentrea en el tablero del transportador. Luego con una plataforma suba hasta la altura donde se encuentra el motor electrico con su respectiva caja reductora. Esta caja tiene un tapon en la parte inferior para drenar el aceite usado y otro tapon en la parte superior para cargarla con aceite. Como primer paso drene el aceite viejo colocando un contenedor debajo. Una vez el aceite es drenado, coloque el aceite nuevo por el tapon de llenado, siendo la misma cantidad la que se dreno.','Plataforma elevadora, trapos, juego de llaves allen, destornillador philips y destornillador plano.','ISO VG 320 (EP) o ISO VG 220 (EP)',43),
  ('HER-ROBS-01','Inspeccion: Regulador','diaria','mantenimiento','Inspeccion','Verifique el caudal en el cuerpo de la antorcha con un regulador de presion','Regulador','El programa de producción especifica el caudal requerido (normalmente de 15 a 25 L/min para MIG/MAG en acero al carbono). Un caudal bajo provoca porosidad; un caudal excesivo genera turbulencias que introducen oxígeno atmosférico en la zona de protección.',null,null,44),
  ('HER-ROBS-01','Inspeccion: Bobina','diaria','mantenimiento','Inspeccion','Compruebe el peso de la bobina para estimar la cantidad de alambre restante, inspeccione el alambre para detectar dobleces o contaminación superficial entre la bobina','Bobina','El rollo de bobina se ira consumiendo a medida que el robot suelde, es de total importancia que se asegure que el alambre que utilizara se encuentra en buenas condiciones y es el del tamaño adecuado.',null,'Rollo de alambre de 1mm',45),
  ('HER-ROBS-01','Inspeccion: Masa o retorno de soldadura.','diaria','mantenimiento','Inspeccion','Es importante mantener la abrazadera en optimas condiciones, ya que, el circuito de soldadura es un bucle cerrado, la corriente sale de la fuente, pasa por la antorcha, forma el arco en la pieza y debe regresar a la fuente a través del retorno. Si la masa está sucia, sulfatada o floja, se genera una resistencia que degrada la calidad del trabajo y daña el equipamiento.','Masa o retorno de soldadura.','Compruebe que la superficie de contacto de la abrazadera esté limpia, que la terminación del cable esté bien ajustada y que la abrazadera esté colocada lo más cerca posible de la junta de soldadura',null,null,46),
  ('HER-ROBS-01','Limpieza: Torcha','diaria','mantenimiento','Limpieza','La acumulación de salpicaduras restringe el flujo de gas y provoca cortocircuitos que generan defectos de soldadura y desconectan la fuente de alimentación.','Torcha','Elimine las salpicaduras de soldadura del orificio de la boquilla, la cara del difusor de gas y el asiento de la punta de contacto.','Tobera','Limpiador de tobera, trapos',47),
  ('HER-ROBS-01','Inspeccion: Topes mecanicos de los ejes','diaria','mantenimiento','Inspeccion','La inspección de los topes de los ejes es una prueba de seguridad crítica para evitar que el robot sobrepase su zona de trabajo segura, colisione contra la celda o arranque el paquete de cables','Topes mecanicos de los ejes','Inspeccione visualmente los topes meacanicos de cada eje del robot, apague la alimentacion del robot y asegurese que los topes no se encuentren flojos, dañados o doblados.',null,null,48),
  ('HER-ROBS-01','Inspeccion: Deposito refrigerante','diaria','mantenimiento','Inspeccion','Compruebe el nivel del depósito de refrigerante. Un nivel bajo de refrigerante provoca el sobrecalentamiento de la antorcha, lo que deteriora el cuerpo de la misma, acorta la vida útil del revestimiento y, en casos graves, anula la garantía de la fuente de alimentación por fallos en la antorcha.','Deposito refrigerante','Asegurese que el deposito refrigerante que se encuentra en el equipo soldador, se encuentre lleno con agua destilada para que la antorche pueda refrigerarse de modo correcto.',null,'Agua destilada',49),
  ('HER-ROBS-01','Reemplazo: Pico de antorcha (Semanal (50hs arco activo))','semanal','mantenimiento','Reemplazo','Orificio ovalado o deformado por fricción, micro-pegaduras del alambre dentro del pico, arco inestable o falta de penetración.','Pico de antorcha','Corte la corriente de la maquina directamente del tablero. Comience desenroscando la tobera de forma lenta y tirando hacia abajo, proceda con el corte del sobrante de alambre al ras del pico. Luego con una pinza tome por las caras planas al pico y desenrosque cuidadosamente, aproveche y limpie la rosca del difusor. Luego enrosque el pico nuevo con la mano hasta que sienta que haga tope, termina de enroscar con la pinza sin realizar una fuerza excesiva y finalmente reinstala la tobera.','Pinza cuadrada, trapos, guantes','Pico de antorcha',50),
  ('HER-ROBS-01','Inspeccion: Rodillo de alimentacion','semanal','mantenimiento','Inspeccion','Examine el perfil de la ranura del rodillo de accionamiento en la superficie de contacto con el alambre. Las ranuras desgastadas con un perfil plano o abombado no sujetan el alambre de forma uniforme, lo que provoca interrupciones en la alimentación del alambre y, en consecuencia, una deposición irregular y discontinuidades en la soldadura. Reemplace los rodillos en pares cuando observe desgaste.','Rodillo de alimentacion','Con una escalera suba hasta el gabinete por donde pasa el alambre, abra la pestaña de la ventana y comrpuebe que el alambre se desliza correctamente a traves de los rodillos. Puede agregar alambre a traves del equipo de soldadura para verificar el funcionamiento de los rodillos','Escalera',null,51),
  ('HER-ROBS-01','Limpie el gabinete de control electrico: Gabinete de potencia y gabinete de control','mensual','mantenimiento','Limpie el gabinete de control electrico','Aspirado de polvo y reapriete de conexiones para evitar falsos contactos','Gabinete de potencia y gabinete de control','Corte la termica general que energiza al robot. Asegurese que los componentes se encuentran en buen estado y no existe sobrecalentamiento dentro del gabinete, ademas con un taladro electrico y guantes de seguridad realice el reaprite de conexiones de las borneras, debido a que con las vibraciones se pueden aflojar y crear falsos contactos.','Taladro electrico',null,52),
  ('HER-ROBS-01','Inspeccion: Parada de emergencia','mensual','mantenimiento','Inspeccion','Compruebe que tanto la parada de emergencia del teach pendant, asi como el del gabinete del robot funcionan correctamente','Parada de emergencia','Realice una prueba con el robot en modo manual para poder comprobar que el pulsador de emergencia funciona correctamente.',null,null,53),
  ('HER-ROBS-01','Verifique el TCP: TCP','mensual','mantenimiento','Verifique el TCP','Mueva el robot a su posición de verificación TCP y compruebe el punto central de la herramienta con respecto al pasador de referencia o al objetivo TCP maestro','TCP','Lleve la punta del robot, con el alambre incluido, hasta el punto de referencia TCP, luego con el sistema de coordenada puesto debe realizar movimientos de pivote sobre la misma punta de la antorcha.',null,null,54),
  ('HER-ROBS-01','Deteccion: Tubo de gas','mensual','mantenimiento','Deteccion','La deteccion de fuga es clave, ya que al existir una fuga en el cabezal o regulador de gas esto genera un efecto negativo en el resultado final de la soldadura. Ademas, existe un desperdicio economico del gas y aprovechamos al 100% la vida util del cabezal regulador.','Tubo de gas','Mezcle agua con jabon, y pase en las conexiones de mangueras que tenga  para comprobar que no existe fuga de gas.','Jabon, agua.',null,55),
  ('HER-ROBS-01','Remplazo: Tobera','mensual','mantenimiento','Remplazo','Acumulación severa de proyecciones que obstruya el flujo de gas, deformación física o fugas de gas por mala rosca/asiento.','Tobera','Corte la corriente de la maquina directamente del gabinete, una vez la tobera enfriada con la temperatura ambiente, desenrosquela con cuidado. Una vez retirada limpie el pico de contacto y el difusor de gas, retirandole el ollin y restos de soldadura. Con la zona ya limpia busque la nueva tobera y enrosque con cuidado sin demasiado fuerza para no barrer ninguna rosca.','pinza cuadrada, trapos, guantes','Tobera',56),
  ('HER-ROBS-01','Reemplazo: Difusor de gas (portapico)','trimestral','mantenimiento','Reemplazo','Rosca barrida, picaduras por calor intenso o poros obstruidos que no se pueden limpiar.','Difusor de gas (portapico)','Corte la corriente de la maquina directamente del tablero, una vez la tobera enfriada con la temperatura ambiente, desenrosquela con cuidado. Una vez retirada limpie el pico de contacto y el difusor de gas, retirandole el ollin y restos de soldadura. Con la zona ya limpia, desenrosque el difusor del cuello de la antorcha, limpie el cuello y la rosca de la antorcha antes de montar el repuesto, una vez la zona limpia ajuste con los dedos al difuros, luego termine de ajustar con una pinza, finalmente reinstale la tobera y el pico de la antorcha.','Pinza cuadrada, trapos, guantes','Difusor de gas',57),
  ('HER-ROBS-01','Inspeccion: Pilas AA','trimestral','mantenimiento','Inspeccion','Sustituya las baterías de respaldo del codificador absoluto en todos los ejes. La duración de la batería suele ser de 2 a 3 años a temperatura ambiente normal, pero las temperaturas ambiente elevadas (superiores a 40 °C) la reducen. Una batería del codificador agotada provoca la pérdida total de la referencia de posición del robot en el siguiente ciclo de encendido, lo que requiere una calibración completa del punto cero, que normalmente dura entre dos y cuatro horas. Sustituir las baterías periódicamente resulta mucho más económico.','Pilas AA','Con el robot encendido, abra el gabinete del robot, en la parte de control encontrara las borneras con las baterias AA que controlan la posicion de los encoders. Pulse el boton de emergencia del teach pendant para asegurar que ningun eje se mueva. A continuacion, saque las pilas y pongas las nuevas. Finalemente reinice el robot.',null,'Pilas AA',58),
  ('HER-ROBS-01','Cambio de grasa: Cajas reductoras','anual','mantenimiento','Cambio de grasa','Inspeccione el estado de la grasa (un cambio de color indica exposición al calor o contaminación), el estado de las estrías flexibles del engranaje (busque desgaste por fricción en la superficie exterior de las estrías flexibles) y la holgura del cojinete de salida. Reemplace la grasa con el volumen y el tipo especificados para cada eje.','Cajas reductoras','En cada eje se encuentra un adhesivo (oil filller) que indica por donde se debe colocar el aceite, y otro adhesivo (oil drain) que indica por donde expulsar. Debera abrir el tornillo tipo allen que se ve, drenar el aceite viejo y luego rellenar con aceite nuevo. El aceite que debe usar grasa de grado NLGI 0','Juego de llaves allen, trapo','Grasa grado NLGI 0',59),
  ('HER-SIEH-01','Inspeccion: Deposito de liquido refrigerante','semanal','mantenimiento','Inspeccion','Verifique visualmente el nivel de refrigerante, debido a que un corte seco daña la hoja y deja una mala terminacion','Deposito de liquido refrigerante','Abra la tapa del deposito refrigerante sacando los 4 tornillos allen que se encuentran en sus esquinas, verifique el nivel de refrigerante y el estado en el que se encuentra, en caso que el nivel sea bajo, utilice agua destilada y aceite soluble refrigerante en una proporcion 95% 5% para rellenar de nuevo el deposito','Juego de llave allen','Liquido refrigerante',60),
  ('HER-SIEH-01','Limpieza: Valvulas neumaticas','semanal','mantenimiento','Limpieza','Limpie el gabinete del control neumatico de la sierra, el mismo dentro tiene dos valvulas que controlan el flujo de aire del sistema de la sierra, asegurese que se encuentra limpio y en buen estado.','Valvulas neumaticas','En uno de los laterales se encuentran las valvulas neumaticas que controlan la apertura de las mordazas, abra el gabinete y limpie cuidadosamente las valvulas, las mismas no deben de presentar aceite ni agua sobre si ni a sus alrededores.','Trapos.',null,61),
  ('HER-SIEH-01','Drenaje: Filtros de aire','mensual','mantenimiento','Drenaje','Purgue el agua de los filtros de aire de control neumatico. Esto evita la corrosion de las valvulas','Filtros de aire','Dentro del gabinete se encuentra el filtro de aire, en su parte inferior cuenta con una valvula, abrala para purgar todo el agua que acumula el sistema.',null,null,62),
  ('HER-SIEH-01','Limpieza: Filtro de refrigerante','mensual','mantenimiento','Limpieza','Limpie el filtro de la bomba para que no se obstruya por el acumulamiento de viruta','Filtro de refrigerante','Limpie el filtro por donde ingresa el liquido refrigerante cuando es utilizado. Asegurese de dejarlo en buenas condiciones para que cumpla su funcion de manera optima',null,null,63),
  ('HER-SIEH-01','Limpieza: Tablero electrico, control neumatico','mensual','mantenimiento','Limpieza','Aspirado de polvo y reapriete de conexiones para evitar falsos contactos. Control de perdidas de electrovalvulas.','Tablero electrico, control neumatico','Corte la energia  con la llave termomagnetica. Asegurese que los componentes se encuentran en buen estado y no existe sobrecalentamiento dentro del gabinete, ademas con un taladro electrico y guantes de seguridad realice el reaprite de conexiones de las borneras, debido a que con las vibraciones se pueden aflojar y crear falsos contactos. Ademas abra el gabinete donde se encuentran las electrovalvulas que controlan el flujo de aceite, limpie el exedente y la mugre que se encuentran sobre las mismas','Trapos, taladro electrico, guantes, puntera philips',null,64),
  ('HER-SIEH-01','Inspeccion: Sierra circular de corte, acero HSS PULSAR 450 x 3,5 x 50','mensual','mantenimiento','Inspeccion','El disco de corte no debe de tener fisuras y no le debe de faltar dientes, en el caso que falten, cambie la hoja.','Sierra circular de corte, acero HSS PULSAR 450 x 3,5 x 50','Con la maquina apagada, verifique que la sierra no esta agrietada y no tiene faltante de dientes. En caso que se encuentre dañada, retirela y cambie de sierra por una nueva, debe aflojar el tornillo allen que la sostiene para poder retirarla.','Trapos, juego de llaves allen',null,65),
  ('HER-SIEH-01','Inspeccion: Deposito de liquido refrigerante','trimestral','mantenimiento','Inspeccion','Si bien se debe de limpiar el filtro para que cumpla con su trabajo, por el mismo pasan virutas finas o sedimentos que se iran filtrando y reposaran en el fondo del tanque refrigerante. Este tanque, debera ser limpiado para asegurar un correcto flujo de refrigerante. Cuidando de esta manera la bomba que hace circular el liquido.','Deposito de liquido refrigerante','Con un destornillador Philips, retire la tapa del deposito, una vez vaciado de todo el liquido refrigerante realice una limpieza del deposito para que los sedimentos que se estancan en el fondo no dañen a la bomba.','Destornillador philips, espatula, trapo, juego llave allen',null,66),
  ('HER-SIEH-01','Cambio de refrigerante: Agua destilada y aceite soluble refrigerante.','trimestral','mantenimiento','Cambio de refrigerante','Aproveche la limpieza del deposito  refrigerante para cambiar el liquido, debido a que este, al tener virutas y particulas que adquiere con el tiempo, puede llegar a obstruir la bomba, ademas puede acumular bacterias y perder sus propiedades. En la parte trasera de la maquina se encuentra la bomba con el deposito, debe de sacar los tornillos de la tapa para poder acceder al interior del deposito.','Agua destilada y aceite soluble refrigerante.','En la parte trasera de la maquina se encuentra la bomba con el deposito, debe de sacar los tornillos de la tapa para poder acceder al interior del deposito. Luego, para rellenar el refrigerante, debera de usar aceite soluble y agua mezclados en una proporcion de 5% 95%, purgando de aire el sistema y dejandolo solo con el refrigerante.','Destornillador Philips','Agua destilada, aceite soluble refrigerante',67),
  ('HER-MESB-M1','Inspeccion: Llave selectora, pulsadores NA','mensual','mantenimiento','Inspeccion','Compruebe el funcionamiento de las selectoras y el boton de seguridad','Llave selectora, pulsadores NA','Con la mesa de trabajo vacia, compruebe que las selectoras cambian de motor y las pedaleras cambian el sentido de giro. En caso que deba cambiar las selectoras porque cumplieron con su vida util, debera retirarlas y colocar nuevas con un destornillador philips','Destornillador Philips','Llave selectora, pulsadores NA',68),
  ('HER-MESB-M1','Inspeccion: Cable canal','mensual','mantenimiento','Inspeccion','Inspeccione visualmente el estado en el que se encuentra el cable canal por donde pasaran los cables de los encodres y motores, que se dirigen hasta el mando de control de las mesas.','Cable canal','Retire la tapa del cable canal que se encuentra en el pise y asegure que los cables provenientes de la mesa no presentan fisuras y roces.',null,null,69),
  ('HER-MESB-M1','Limpieza: Pedaleras NA','mensual','mantenimiento','Limpieza','Si uno de los pedales queda pegado existe la posibilidad que la mesa nunca se frene en la direccion en la que se estaba utilizando y esto provoque un accidente.','Pedaleras NA','Con un destornillador philips abra las pedaleras extrayendo su carcasa. Conmunmente, dentro, tienen un contacto que puede quedar pegado si se utilizan en un entorno ostil como el nuestro. Limpielo y compruebe su funcionamiento','Destornillador Philips, trapo','Pedalera NA',70),
  ('HER-MESB-M1','Inspeccion: Mesa de trabajo','mensual','mantenimiento','Inspeccion','Con el paso del tiempo y el uso, estas mesas presentan vibraciones lo cual puede provocar que se aflojen sus tornillos allen que la sujetan a una brida.','Mesa de trabajo','Con el sistema apagado, pruebe realizar fuerza sobre la mesa de trabajo para verificar que se encuentra apretada correctamente. La misma no debe de presentar ningun juego entre la brida de sujecion y la mesa propiamente dicha','Juego llave allen',null,71),
  ('HER-BOXH-01','Inspeccion: Regulador de presion','mensual','mantenimiento','Inspeccion','El regulador de presion es el responsable de llevar la presion de aire justa hacia el cilindro y hacia la cuba.','Regulador de presion','Comprueba que los dos reguladores de presion se encuentran en buen estado. Tire del cabezal hacia arriba y cambie los valores de presion para comprobar su fucionamiento. Vea que sus racores tengan el teflon en buen estado y no pierdan aire.','Pulsiana, trapo, teflon',null,72),
  ('HER-BOXH-01','Inspeccion: Valvula de control 3/2','mensual','mantenimiento','Inspeccion','Verifique que la valvula de control se encuentra en optimas condiciones, la misma es la responsable de conmutar los estados del cilindro.','Valvula de control 3/2','Compruebe que la valvula de control 3/2 conmuta ambos estados que puede tomar el cilindro, y que sus escapes funcionan expulsan el aire sin ningun tipo de agua condensada. Vea que sus racores tengan el teflon en buen estado y no pierda aire','Pulsiana, trapo, teflon',null,73),
  ('HER-BOXH-01','Inspeccion: Mesa movil','mensual','mantenimiento','Inspeccion','El nitrilo pegado sobre la mesa de trabajo es el encargado de generar el sellado de la cuba.','Mesa movil','Retire la mesa fuera de la zona de trabajo del cilindro, procure realizar una inspeccion visual del nitrilo pegado sobre la chapa. Si observa que el mismo esta muy desgastado, debe retirarlo y cambiarlo por uno nuevo.','Espatula, pegamento.','Rollo nitrilo de 10mm',74),
  ('HER-BOXH-01','Inspeccion: Valvulas de control de caudal','mensual','mantenimiento','Inspeccion','Inspeccione y verifique que las valvulas de control de caudal que se encuentran en la entrada del cilindro FESTO, se encuentran en buen estado y pueden ser reguladas para cambiar la velocidad del cilindro.','Valvulas de control de caudal','Con una escalera, suba hasta la altura del cilindro, en la entrada y salida de aire del mismo, se encuentra un adaptador de rosca junto con una valvula que regula el caudal de aire. Estos son los encargados de regular la velocidad con la que bajara y subira el cilindro. Compruebe con un destornillador plano y con la mesa de trabajo retirada, que las valvulas se encuentran en buenas condiciones y pueden regular la velocidad.','Escalera, teflon, pulsiana, destornillador plano.',null,75),
  ('HER-BOXH-01','Inspeccion de mangueras de aire: Tubo manguera poliuretano 8mm','mensual','mantenimiento','Inspeccion de mangueras de aire','Inspeccione y verifique que las mangueras que transportan el aire comprimido no estan duras ni agrietadas','Tubo manguera poliuretano 8mm','Verifique que todos los tramos de maguera se encuentran en buenas condicioness, no estan duras y no presentan grietas.',null,null,76),
  ('SRV-AIRE-01','Controlar: Aceite del compresor','diaria','mantenimiento','Controlar','Verifique el nivel de aceite','Aceite del compresor',null,null,null,77),
  ('SRV-AIRE-01','Controlar: Cables de alimentacion de energia, mangueras de aceite y aire.','semanal','mantenimiento','Controlar','Funcionamiento de inicio de maquina..','Cables de alimentacion de energia, mangueras de aceite y aire.','Verifique visualmente el estado de los cables del aire comprimido, asi tambien como sus mangueras-+.',null,null,78),
  ('SRV-AIRE-01','Limpieza: Filtro de aceite','semanal','mantenimiento','Limpieza','Limpieza filtro de aceite','Filtro de aceite','Remueva el filtor de aceite y limpielo cuidadosamente sin dejar ningun tipo restos de material.',null,'Trapos.',79),
  ('SRV-AIRE-01','Inspeccion: Tanque de aceite','semanal','mantenimiento','Inspeccion','Inspeccion de acumulacion de agua en el tanque de separacion de aceite','Tanque de aceite','En caso que observe que existe agua en el deposito de aceite, abralo y drene cuidadosamente el agua que estara separada.',null,null,80),
  ('SRV-AIRE-01','Limpieza: Enfriador','semanal','mantenimiento','Limpieza','Limpieza del enfriador (cooler)','Enfriador','Limpie las manchas de aceite del enfriador',null,'Trapo',81),
  ('SRV-AIRE-01','Limpieza: Gabinete, filtro de polvo','semanal','mantenimiento','Limpieza','Limpieza de filtro de polvo','Gabinete, filtro de polvo','Abra las puertas de los paneles y controle si hay mucha cantidad de polvo dentro, si el filtro de polvo esta excedido de polvo limpielo con aire comprimido','Aire comprimido.',null,82),
  ('SRV-AIRE-01','Cambio: Filtro de aceite (500 horas)','trimestral','mantenimiento','Cambio','Inspeccion de filtro de aceite','Filtro de aceite','Remueva el filtro de aceite del gabinete y reemplacelo a las primeras 500 horas de uso',null,'Filtro de aceite',83),
  ('SRV-AIRE-01','Limpieza: Filtro de aire (500 horas)','trimestral','mantenimiento','Limpieza','Limpieza de filtro de aire','Filtro de aire','Luego de 500 horas de uso de la maquina, remueva el filtro de aire  y limpielo de adentro hacia afuera con aire comprimido, eliminando asi todas las particulas de polvo que atrapo.',null,null,84),
  ('SRV-AIRE-01','Cambio: Filtro de aceite (2000 horas)','anual','mantenimiento','Cambio','Inspeccion de filtro de aceite','Filtro de aceite','Remueva el filtro de aceite del gabinete y reemplacelo luego de 2000 horas de uso.',null,'Filtro de aceite',85);

-- 6) Catálogo de repuestos / partes (61 componentes) ---------------------
delete from public.mant_componentes where activo_id in ('HER-AUTO-R1','HER-BOXH-01','HER-MALA-01','HER-MESB-M1','HER-RACK-01','HER-ROBS-01','HER-ROLA-01','HER-SIEH-01','HER-TRAN-01','SRV-AIRE-01','SRV-GRUA-01');
insert into public.mant_componentes (activo_id, cantidad, nombre, foto_path, orden) values
  ('HER-RACK-01','6','Motor eléctrico','componentes/rack_automatico_de_chapas__motor_electrico.jpg',0),
  ('HER-RACK-01','1','Control inalámbrico','componentes/rack_automatico_de_chapas__control_inalambrico.jpg',1),
  ('HER-RACK-01','2','Sensor inductivo','componentes/rack_automatico_de_chapas__sensor_inductivo.jpg',2),
  ('HER-RACK-01','12','Final de carrera YBLX-ME/8108','componentes/rack_automatico_de_chapas__final_de_carrera_yblx_me_8108.jpg',3),
  ('HER-RACK-01','1','Térmica D10 y fusible chint 32A','componentes/rack_automatico_de_chapas__termica_d10_y_fusible_chint_32a.jpg',4),
  ('HER-RACK-01','24','Rodamientos UC 205 o YAR 20','componentes/rack_automatico_de_chapas__rodamientos_uc_205_o_yar_20.jpg',5),
  ('HER-RACK-01','6','Cajas reductoras T2  - 1:2 – U-LR','componentes/rack_automatico_de_chapas__cajas_reductoras_t2_1_2_u_lr.jpg',6),
  ('HER-AUTO-R1','1','Pico de antorcha','componentes/soldadora_automatica__pico_de_antorcha.jpg',7),
  ('HER-AUTO-R1','1','Difusor','componentes/soldadora_automatica__difusor.jpg',8),
  ('HER-AUTO-R1','1','Tobera','componentes/soldadora_automatica__tobera.jpg',9),
  ('HER-AUTO-R1','8','Patines para guías lineales','componentes/soldadora_automatica__patines_para_guias_lineales.jpg',10),
  ('HER-AUTO-R1','1','Caja reductora','componentes/soldadora_automatica__caja_reductora.jpg',11),
  ('HER-AUTO-R1',null,'Rodamientos','componentes/soldadora_automatica__rodamientos.jpg',12),
  ('HER-AUTO-R1','1','Tubo de gas','componentes/soldadora_automatica__tubo_de_gas.jpg',13),
  ('SRV-GRUA-01','1','Motor 30A 380V 13kW 1400RPM','componentes/puente_grua_10t__motor_30a_380v_13kw_1400rpm.jpg',14),
  ('SRV-GRUA-01','2','Motor 2,4 A 380V 0,8 kW 1380 RPM',null,15),
  ('SRV-GRUA-01','2','Motor 8,5 A 380V 1,5kW 1380 RPM',null,16),
  ('SRV-GRUA-01','1','gancho 10T','componentes/puente_grua_10t__gancho_10t.jpg',17),
  ('SRV-GRUA-01','1','Tablero eléctrico (potencia y comando)',null,18),
  ('HER-MALA-01','1','Gancho de carga','componentes/malacate_1000kg__gancho_de_carga.jpg',19),
  ('HER-MALA-01','1','Control inalámbrico','componentes/malacate_1000kg__control_inalambrico.jpg',20),
  ('HER-MALA-01','1','Motor eléctrico','componentes/malacate_1000kg__motor_electrico.jpg',21),
  ('HER-TRAN-01','1','Riel IPN','componentes/transportador_aereo__riel_ipn.jpg',22),
  ('HER-TRAN-01','1','Soportes de fundición','componentes/transportador_aereo__soportes_de_fundicion.jpg',23),
  ('HER-TRAN-01','1','Rueda guía','componentes/transportador_aereo__rueda_guia.jpg',24),
  ('HER-TRAN-01','1','Eslabón de cadena','componentes/transportador_aereo__eslabon_de_cadena.jpg',25),
  ('HER-TRAN-01','1','Caja reductora','componentes/transportador_aereo__caja_reductora.jpg',26),
  ('HER-TRAN-01','1','Motor','componentes/transportador_aereo__motor.jpg',27),
  ('HER-ROBS-01','1','Regulador','componentes/robot_soldador__regulador.jpg',28),
  ('HER-ROBS-01','1','Bobina de alambre','componentes/robot_soldador__bobina_de_alambre.jpg',29),
  ('HER-ROBS-01','1','Torcha de soldadura','componentes/robot_soldador__torcha_de_soldadura.jpg',30),
  ('HER-ROBS-01','1','Pico Mig 1mm','componentes/robot_soldador__pico_mig_1mm.jpg',31),
  ('HER-ROBS-01','1','Difusor','componentes/robot_soldador__difusor.jpg',32),
  ('HER-ROBS-01','1','Difusor cerámico','componentes/robot_soldador__difusor_ceramico.jpg',33),
  ('HER-ROBS-01','1','Porta Pico','componentes/robot_soldador__porta_pico.jpg',34),
  ('HER-ROBS-01','1','Tobera busa','componentes/robot_soldador__tobera_busa.jpg',35),
  ('HER-ROBS-01','6','Topes mecánicos','componentes/robot_soldador__topes_mecanicos.jpg',36),
  ('HER-ROBS-01','2','Rodillos',null,37),
  ('HER-ROBS-01','1','Gabinete potencia','componentes/robot_soldador__gabinete_potencia.jpg',38),
  ('HER-ROBS-01','1','Calibrador de TCP','componentes/robot_soldador__calibrador_de_tcp.jpg',39),
  ('HER-ROBS-01','1','Tubo de Gas','componentes/robot_soldador__tubo_de_gas.jpg',40),
  ('HER-ROBS-01','6','Cajas reductoras (llenado y vaciado de aceite)','componentes/robot_soldador__cajas_reductoras_llenado_y_vaciado_d.jpg',41),
  ('HER-ROBS-01','6','Cajas reductoras (llenado y vaciado de aceite)','componentes/robot_soldador__cajas_reductoras_llenado_y_vaciado_d_2.jpg',42),
  ('HER-ROBS-01','1','Teach Pendant','componentes/robot_soldador__teach_pendant.jpg',43),
  ('HER-SIEH-01','1','Depósito de líquido refrigerante','componentes/sierra_hidraulica__deposito_de_liquido_refrigerante.jpg',44),
  ('HER-SIEH-01','2','Válvula neumática','componentes/sierra_hidraulica__valvula_neumatica.jpg',45),
  ('HER-SIEH-01','1','Filtro de aire','componentes/sierra_hidraulica__filtro_de_aire.jpg',46),
  ('HER-SIEH-01','1','Filtro refrigerante','componentes/sierra_hidraulica__filtro_refrigerante.jpg',47),
  ('HER-SIEH-01','1','Gabinete eléctrico','componentes/sierra_hidraulica__gabinete_electrico.jpg',48),
  ('HER-SIEH-01','1','Sierra de corte HSS 450 x 3,5 x 50','componentes/sierra_hidraulica__sierra_de_corte_hss_450_x_3_5_x_50.jpg',49),
  ('HER-MESB-M1','4','Llaves selectoras','componentes/mesa_soldadura_pivotante__llaves_selectoras.jpg',50),
  ('HER-MESB-M1','2','Pulsador NA','componentes/mesa_soldadura_pivotante__pulsador_na.jpg',51),
  ('HER-MESB-M1','4','Pedales NA','componentes/mesa_soldadura_pivotante__pedales_na.jpg',52),
  ('HER-BOXH-01','2','Regulador de presión','componentes/box_hermeticidad__regulador_de_presion.jpg',53),
  ('HER-BOXH-01','1','Válvula de control 3/2','componentes/box_hermeticidad__valvula_de_control_3_2.jpg',54),
  ('HER-BOXH-01','2','Válvula de control de caudal','componentes/box_hermeticidad__valvula_de_control_de_caudal.jpg',55),
  ('HER-BOXH-01','10m','Tubo manguera poliuretano 8mm','componentes/box_hermeticidad__tubo_manguera_poliuretano_8mm.jpg',56),
  ('HER-ROLA-01','4','Rodillos móviles','componentes/roladora__rodillos_moviles.jpg',57),
  ('HER-ROLA-01','14','Electroválvulas','componentes/roladora__electrovalvulas.jpg',58),
  ('HER-ROLA-01','1','Filtro de aceite','componentes/roladora__filtro_de_aceite.jpg',59),
  ('HER-ROLA-01','1','Tablero eléctrico','componentes/roladora__tablero_electrico.jpg',60);

-- Verificación:
-- select activo_id, count(*) from mant_gamas where ejecucion is not null group by 1;
-- select activo_id, count(*) filter (where foto_path is not null) fotos, count(*) from mant_componentes group by 1;
